pluginStuff:
  noPermissionMessage: '&c대화를 전송하지 못했습니다. 대화를 전송할 권한이 없습니다'
  reloadMessage: '구성을 성공적으로 로드했습니다'

globalLocalChat:
  globalChat: '기본 대화 모드를 &7[전체]&f으(로) 변경했습니다'
  alreadyInGlobalChat: '&c변경 사항이 없습니다. 이미 해당 대화 모드가 기본값입니다'
  permToTypeInGlobalChat: true
  staffChat: '기본 대화 모드를 &c[스태프]&f으(로) 변경했습니다'
  alreadyInStaffChat: '&c변경 사항이 없습니다. 이미 해당 대화 모드가 기본값입니다'
  spyLocalOnLogin: true
  spyLocalOn: '지역 대화를 염탐합니다'
  spyLocalOff: '지역 대화 염탐을 종료합니다'
  spyLocalPrefix: '&8[&cLocal Spy&8]&7 '
  localChat: '기본 대화 모드를 &2[지역]&f으(로) 변경했습니다'
  alreadyInLocalChat: '&c변경 사항이 없습니다. 이미 해당 대화 모드가 기본값입니다'
  permToSeeLocalChat: true
  localChatRadius: 1000
  localChatPrefix: '-> &2[&2지역&2]&f '
  globalChatPrefix: '&7'
  staffChatPrefix: '&7[ &c스태프 &7]&f '